import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Hero from '@/components/Hero'
import About from '@/components/About'
import Experience from '@/components/Experience'
import Project from '@/components/Project'
import Footer from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Benny Hsiao website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navbar />
      <Hero />
      <About />
      <Experience />
      <Project />
      <Footer />
    </>
  )
}
